### ISSUE TITLE
Document Pure Pursuit tools

### ISSUE THREAD

**Issue by ewpratten** [frc5024/lib5k#103]
This should include:
 - What is PurePursuit?
 - What types of paths can be generated, and how do they differ
 - How to import a PathWeaver path into Lib5K

**Comment by ewpratten** [comment]
@wm-c would you be interested in this?

**Comment by wm-c** [comment]
I can definitely do this one.

**Comment by ewpratten** [comment]
@wm-c These should include some XChart images too
