### ISSUE TITLE
All encoders need to be zeroed on boot

### ISSUE THREAD

**Issue by ewpratten** [frc5024/lib5k#27]
I just noticed from testing encoders on MiniBot that on boot, the sensor keeps its last reading (The robot turned on and had about 10k rotations registered.)

We need something (probably in the CommonEncoder constructor) that takes the current reading, and saves it as an offset, so it will appear to the code that we always start at 0 ticks.

**Comment by ewpratten** [comment]
@wm-c are you interested in fixing this?

**Comment by wm-c** [comment]
@Ewpratten I am interested, I'll get on once I finish the current project
