### ISSUE TITLE
We need a better solution to motorcollections

### ISSUE THREAD

**Issue by ewpratten** [frc5024/lib5k#4]
Not sure how to fix them though... input welcome

**Comment by ewpratten** [comment]
@wm-c have any thoughts?

**Comment by wm-c** [comment]
@Ewpratten I haven't personally used motor collection to much. That being said a lot of my dislike for it is the initial setup and requirement to have multiple collections because each motor act differently.  We could look into making a motor factory, that gives a wrapper class for each motor that implements a standard motor interface.

**Comment by ewpratten** [comment]
I just finished adding wrappers to motors ([code](https://github.com/frc5024/lib5k/blob/master/hardware/ctre/src/main/java/io/github/frc5024/lib5k/hardware/ctre/motors/ExtendedTalonSRX.java), [docs](https://cs.5024.ca/lib5k/io/github/frc5024/lib5k/hardware/ctre/motors/ExtendedTalonSRX.html)) so maybe we can extend this?

**Comment by ewpratten** [comment]
Maybe we can extend WPILib's [SpeedControllerGroup](https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/SpeedControllerGroup.html)?

Really, these are the reasons we need something similar to the collections, and cant just delete them:
 - Need to set multiple motors' outputs with a single method
 - Need to be able to configure an entire gearbox at once instead of motor-by-motor

CTRE has a solution to this with its `follow()` methods. I wonder if we can patch something similar into the [SparkMax extensions](https://github.com/frc5024/lib5k/blob/master/hardware/revrobotics/src/main/java/io/github/frc5024/lib5k/hardware/revrobotics/motors/ExtendedSparkMax.java)?

**Comment by wm-c** [comment]
Definitely, I was thinking more of a common interface however
