### ISSUE TITLE
Add our own scheduler

### ISSUE THREAD

**Issue by wm-c** [frc5024/lib5k#45]
I would like to add a our own scheduler/subsystem looper similar to the team 254.

**Comment by ewpratten** [comment]
I moved this to 1.4.0 because I'd like to get 1.3.0 published tomorrow or monday

**Comment by ewpratten** [comment]
I recommend making your scheduler extend `CommandScheduler` so we can still use commands and subsystems

**Comment by wm-c** [comment]
CommandScheduler is a final class which prevents it from being extended(to my knowledge). My plan was to write a manager similar to 254s.
