### ISSUE TITLE
Add a wrapper around Notifiers

### ISSUE THREAD

**Issue by ewpratten** [frc5024/lib5k#46]
We should implement a wrapper around notifiers that:
 - Automatically names each thread
 - Has the option for error handling in the thread
 - Reflects all errors and exceptions to the log

**Comment by ewpratten** [comment]
boi

**Comment by ewpratten** [comment]
Im in the middle of writing this :laughing:

**Comment by wm-c** [comment]
should've assigned yourself 
i'll grab a different one

**Comment by ewpratten** [comment]
I'll tag you in the review. I have an interesting idea for this that you might like. Sorry about that
