### ISSUE TITLE
Replace StateSpacev1 with newer WPILib statespace utilities

### ISSUE THREAD

**Issue by ewpratten** [frc5024/lib5k#56]
This is waiting on some work to be done upstream because I really don't want to make our team have to worry about JNI code in our library.

This is mostly a thread to track the progress of @mcm001 and @calcmogul's work upstream

**Comment by ewpratten** [comment]
[Stage 0]

[Drake](https://drake.mit.edu/) and [Drake JNI](https://github.com/mcm001/allwpilib/blob/state-space-v2/wpiutil/src/main/java/edu/wpi/first/wpiutil/math/DrakeJNI.java) have been merged upstream in https://github.com/wpilibsuite/allwpilib/pull/2613. We can technically go ahead with pulling in the WPILibJ side of https://github.com/mcm001/allwpilib/tree/state-space-v2 right now, but it will become out-of-date pretty quick

**Comment by mcm001** [comment]
Take a look at the core state-space PR. Note that DRAKE is being moved to wpimath to help prevent some of the insane memory usages we were seeing (up to 3gb per worker), but the Java stuff in that PR is basically done pending final review.

**Comment by ewpratten** [comment]
@mcm001 quick question, v2 doesn't require a python script to generate code, right?

**Comment by calcmogul** [comment]
> v2 doesn't require a python script to generate code, right?

Correct.
