### ISSUE TITLE
Some files need to be added to the gitignore

### ISSUE THREAD

**Issue by ewpratten** [frc5024/lib5k#69]
The following files must be deleted, then added to `.gitignore`:
 - `.settings/org.eclipse.buildship.core.prefs`
 - `imgui.ini`

**Comment by tarishij17** [comment]
Hey team..Is this still open to be picked?

**Comment by tarishij17** [comment]
I want to contribute but not able to commit to this repo, giving permission denied. Could anyone help?

**Comment by tarishij17** [comment]
I've added a PR for this
