### ISSUE TITLE
Create an FAQ in the wiki

### ISSUE THREAD

**Issue by ewpratten** [frc5024/lib5k#82]
The wiki should have a "frequently asked questions" page.

If you don't have anything to add yourself, feel free to just add "work in progress", and I'll add some of my own notes later

**Comment by harshita130602** [comment]
Hey! I would like to contribute to this issue. Could you please assign it to me?

**Comment by ewpratten** [comment]
As an outside contributor, do you have wiki access?

**Comment by harshita130602** [comment]
No, I don't have access but I think you can grant me access so that I can do this work.

**Comment by ewpratten** [comment]
Since this organization is managed by a school, I unfortunately cannot grant outside people access to internal documents.
